name:                bot
version:             0.1.0.0
github:              "the-toster/ech-bot"
license:             BSD3
author:              "Anton"
maintainer:          "internetov.ru@gmail.com"
copyright:           "2020 Anton"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/bot#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  bot-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot
    - req
    - aeson

tests:
  bot-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - bot
